disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "King's Space"

[params]
displayName = "English"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "/icons/logo.svg"
secondaryLogo = "/icons/logo.svg"
copyright = ":copyright: { year } King Zang"
description = ""

[params.author]
name = "King Zang"
email = "zangking@outlook.com"
image = "/img/mozart.jpg"
imageQuality = 96
headline = "Always learn..."
bio = "B4 @ BUPT CS; Incoming PhD @ ZGCA"

[[params.author.links]]
email = "mailto:zangzeyuan@bupt.edu.cn"

[[params.author.links]]
email = "mailto:zangking001@gmail.com"

[[params.author.links]]
link = "https://zzyking.github.io/"

[[params.author.links]]
github = "https://github.com/zzyking"

[[params.author.links]]
x-twitter = "https://x.com/KingZang2"

[[params.author.links]]
steam = "https://steamcommunity.com/profiles/76561199544831479/"