[[main]]
none = "none"

[[main]]
name = "Posts"
pageRef = "posts"
identifier = "kuf3MU2mYl"
weight = 1

[[main]]
name = "Projects"
pageRef = "projects"
identifier = "PIrQYKeFWj"
weight = 2

[[main]]
name = "About"
url = "https://zzyking.github.io/"
identifier = "vUgIt4roCR"
weight = 3

[[main]]
identifier = "tag"
pre = "tag"
title = "Tags"
url = "/tags/"
weight = 4

[[main]]
identifier = "github"
pre = "github"
title = "GitHub"
url = "https://github.com/zzyking/kingz.space"
weight = 5

[[footer]]
none = "none"
